spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/chat_app_db
    username: postgres
    password: 1017#Thugger
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080